version: '3'
services:
  database:
    image: postgres
    container_name: blog-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: bruhh
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest_playground
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
